import { StateGraph, StateSchema, START, END, type GraphNode } from "@langchain/langgraph"
import z from "zod"
import { mistralAiModel, cohereModel, groqModel } from "./model.ai.js"
import { createAgent, HumanMessage, toolStrategy } from "langchain"

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),

    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})

const solutionNode: GraphNode<typeof state> = async (state) => {
    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralAiModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistralResponse,
        solution_2: cohereResponse.text,
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    const judge = createAgent({
        model: groqModel,
        responseFormat: toolStrategy(
            z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_reasoning: z.string(),
                solution_2_reasoning: z.string(),
            })
        ),
        systemPrompt: `
You are a judge tasked with evaluating two solutions generated by different AI models.
Please provide a score out of 10 for each solution, along with your reasoning for the scores.
        `
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
Problem: ${problem}

Solution 1:
${solution_1}

Solution 2:
${solution_2}

Please evaluate the solutions and provide scores and reasoning.
            `)
        ]
    })

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = judgeResponse.structuredResponse

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judgeNode", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judgeNode")
    .addEdge("judgeNode", END)
    .compile()

export default async function (problem: string) {
    const result = await graph.invoke({
        problem: problem
    })

    return result
}